[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "appearance-packing"
publish.workspace = true
version = "0.1.0"

[dependencies]
bytemuck.workspace = true
glam.workspace = true