[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "appearance-build"
publish.workspace = true
version = "0.1.0"

[dependencies]
appearance-asset-database.workspace = true

xshell.workspace = true