[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "appearance-path-tracer"
publish.workspace = true
version = "0.1.0"

[dependencies]
appearance-profiling.workspace = true

glam.workspace = true